# Generated by Django 3.2.16 on 2025-02-06 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.RemoveField(
            model_name='walletoperations',
            name='user',
        ),
    ]
